// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"estore-backend/server/models"
)

// ListOrdersOKCode is the HTTP code returned for type ListOrdersOK
const ListOrdersOKCode int = 200

/*
ListOrdersOK Get order list

swagger:response listOrdersOK
*/
type ListOrdersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Order `json:"body,omitempty"`
}

// NewListOrdersOK creates ListOrdersOK with default headers values
func NewListOrdersOK() *ListOrdersOK {

	return &ListOrdersOK{}
}

// WithPayload adds the payload to the list orders o k response
func (o *ListOrdersOK) WithPayload(payload []*models.Order) *ListOrdersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list orders o k response
func (o *ListOrdersOK) SetPayload(payload []*models.Order) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListOrdersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Order, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
ListOrdersDefault Error

swagger:response listOrdersDefault
*/
type ListOrdersDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListOrdersDefault creates ListOrdersDefault with default headers values
func NewListOrdersDefault(code int) *ListOrdersDefault {
	if code <= 0 {
		code = 500
	}

	return &ListOrdersDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list orders default response
func (o *ListOrdersDefault) WithStatusCode(code int) *ListOrdersDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list orders default response
func (o *ListOrdersDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list orders default response
func (o *ListOrdersDefault) WithPayload(payload *models.Error) *ListOrdersDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list orders default response
func (o *ListOrdersDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListOrdersDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
