// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"estore-backend/server/models"
)

// AddPaymentCreatedCode is the HTTP code returned for type AddPaymentCreated
const AddPaymentCreatedCode int = 201

/*
AddPaymentCreated Created

swagger:response addPaymentCreated
*/
type AddPaymentCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Payment `json:"body,omitempty"`
}

// NewAddPaymentCreated creates AddPaymentCreated with default headers values
func NewAddPaymentCreated() *AddPaymentCreated {

	return &AddPaymentCreated{}
}

// WithPayload adds the payload to the add payment created response
func (o *AddPaymentCreated) WithPayload(payload *models.Payment) *AddPaymentCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add payment created response
func (o *AddPaymentCreated) SetPayload(payload *models.Payment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddPaymentCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
AddPaymentDefault error

swagger:response addPaymentDefault
*/
type AddPaymentDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddPaymentDefault creates AddPaymentDefault with default headers values
func NewAddPaymentDefault(code int) *AddPaymentDefault {
	if code <= 0 {
		code = 500
	}

	return &AddPaymentDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add payment default response
func (o *AddPaymentDefault) WithStatusCode(code int) *AddPaymentDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add payment default response
func (o *AddPaymentDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add payment default response
func (o *AddPaymentDefault) WithPayload(payload *models.Error) *AddPaymentDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add payment default response
func (o *AddPaymentDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddPaymentDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
