// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"estore-backend/server/models"
)

// ListPaymentsOKCode is the HTTP code returned for type ListPaymentsOK
const ListPaymentsOKCode int = 200

/*
ListPaymentsOK Get payment list

swagger:response listPaymentsOK
*/
type ListPaymentsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Payment `json:"body,omitempty"`
}

// NewListPaymentsOK creates ListPaymentsOK with default headers values
func NewListPaymentsOK() *ListPaymentsOK {

	return &ListPaymentsOK{}
}

// WithPayload adds the payload to the list payments o k response
func (o *ListPaymentsOK) WithPayload(payload []*models.Payment) *ListPaymentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list payments o k response
func (o *ListPaymentsOK) SetPayload(payload []*models.Payment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPaymentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Payment, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
ListPaymentsDefault Error

swagger:response listPaymentsDefault
*/
type ListPaymentsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListPaymentsDefault creates ListPaymentsDefault with default headers values
func NewListPaymentsDefault(code int) *ListPaymentsDefault {
	if code <= 0 {
		code = 500
	}

	return &ListPaymentsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list payments default response
func (o *ListPaymentsDefault) WithStatusCode(code int) *ListPaymentsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list payments default response
func (o *ListPaymentsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list payments default response
func (o *ListPaymentsDefault) WithPayload(payload *models.Error) *ListPaymentsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list payments default response
func (o *ListPaymentsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPaymentsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
