// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"estore-backend/server/models"
)

// EditUserHandlerFunc turns a function with the right signature into a edit user handler
type EditUserHandlerFunc func(EditUserParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn EditUserHandlerFunc) Handle(params EditUserParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// EditUserHandler interface for that can handle valid edit user params
type EditUserHandler interface {
	Handle(EditUserParams, *models.Principal) middleware.Responder
}

// NewEditUser creates a new http.Handler for the edit user operation
func NewEditUser(ctx *middleware.Context, handler EditUserHandler) *EditUser {
	return &EditUser{Context: ctx, Handler: handler}
}

/*
	EditUser swagger:route PUT /users/{id} user editUser

Edit user by ID
*/
type EditUser struct {
	Context *middleware.Context
	Handler EditUserHandler
}

func (o *EditUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewEditUserParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
