// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"estore-backend/server/models"
)

// GetOwnUserOKCode is the HTTP code returned for type GetOwnUserOK
const GetOwnUserOKCode int = 200

/*
GetOwnUserOK OK

swagger:response getOwnUserOK
*/
type GetOwnUserOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewGetOwnUserOK creates GetOwnUserOK with default headers values
func NewGetOwnUserOK() *GetOwnUserOK {

	return &GetOwnUserOK{}
}

// WithPayload adds the payload to the get own user o k response
func (o *GetOwnUserOK) WithPayload(payload *models.User) *GetOwnUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get own user o k response
func (o *GetOwnUserOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOwnUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetOwnUserDefault Error

swagger:response getOwnUserDefault
*/
type GetOwnUserDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetOwnUserDefault creates GetOwnUserDefault with default headers values
func NewGetOwnUserDefault(code int) *GetOwnUserDefault {
	if code <= 0 {
		code = 500
	}

	return &GetOwnUserDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get own user default response
func (o *GetOwnUserDefault) WithStatusCode(code int) *GetOwnUserDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get own user default response
func (o *GetOwnUserDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get own user default response
func (o *GetOwnUserDefault) WithPayload(payload *models.Error) *GetOwnUserDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get own user default response
func (o *GetOwnUserDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOwnUserDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
