// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"estore-backend/server/models"
)

// DeleteCategoryNoContentCode is the HTTP code returned for type DeleteCategoryNoContent
const DeleteCategoryNoContentCode int = 204

/*
DeleteCategoryNoContent Deleted

swagger:response deleteCategoryNoContent
*/
type DeleteCategoryNoContent struct {
}

// NewDeleteCategoryNoContent creates DeleteCategoryNoContent with default headers values
func NewDeleteCategoryNoContent() *DeleteCategoryNoContent {

	return &DeleteCategoryNoContent{}
}

// WriteResponse to the client
func (o *DeleteCategoryNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*
DeleteCategoryDefault Error

swagger:response deleteCategoryDefault
*/
type DeleteCategoryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteCategoryDefault creates DeleteCategoryDefault with default headers values
func NewDeleteCategoryDefault(code int) *DeleteCategoryDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteCategoryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete category default response
func (o *DeleteCategoryDefault) WithStatusCode(code int) *DeleteCategoryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete category default response
func (o *DeleteCategoryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete category default response
func (o *DeleteCategoryDefault) WithPayload(payload *models.Error) *DeleteCategoryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete category default response
func (o *DeleteCategoryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCategoryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
