// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"estore-backend/server/models"
)

// DeleteCategoryHandlerFunc turns a function with the right signature into a delete category handler
type DeleteCategoryHandlerFunc func(DeleteCategoryParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCategoryHandlerFunc) Handle(params DeleteCategoryParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteCategoryHandler interface for that can handle valid delete category params
type DeleteCategoryHandler interface {
	Handle(DeleteCategoryParams, *models.Principal) middleware.Responder
}

// NewDeleteCategory creates a new http.Handler for the delete category operation
func NewDeleteCategory(ctx *middleware.Context, handler DeleteCategoryHandler) *DeleteCategory {
	return &DeleteCategory{Context: ctx, Handler: handler}
}

/*
	DeleteCategory swagger:route DELETE /categories/{id} category deleteCategory

Delete category by ID
*/
type DeleteCategory struct {
	Context *middleware.Context
	Handler DeleteCategoryHandler
}

func (o *DeleteCategory) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteCategoryParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
