// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"estore-backend/server/models"
)

// EditCategoryHandlerFunc turns a function with the right signature into a edit category handler
type EditCategoryHandlerFunc func(EditCategoryParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn EditCategoryHandlerFunc) Handle(params EditCategoryParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// EditCategoryHandler interface for that can handle valid edit category params
type EditCategoryHandler interface {
	Handle(EditCategoryParams, *models.Principal) middleware.Responder
}

// NewEditCategory creates a new http.Handler for the edit category operation
func NewEditCategory(ctx *middleware.Context, handler EditCategoryHandler) *EditCategory {
	return &EditCategory{Context: ctx, Handler: handler}
}

/*
	EditCategory swagger:route PUT /categories/{id} category editCategory

Edit category by ID
*/
type EditCategory struct {
	Context *middleware.Context
	Handler EditCategoryHandler
}

func (o *EditCategory) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewEditCategoryParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
