// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Capstone project: back-end",
    "title": "E-Store Back-end",
    "version": "1.0.0"
  },
  "paths": {
    "/auth/cb": {
      "get": {
        "security": [],
        "tags": [
          "auth"
        ],
        "summary": "Obtain access token",
        "operationId": "getAccessToken",
        "responses": {
          "200": {
            "description": "Login",
            "schema": {
              "$ref": "#/definitions/principal"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/categories": {
      "get": {
        "security": [],
        "tags": [
          "categories"
        ],
        "summary": "List categories",
        "operationId": "listCategories",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 24,
            "name": "limit",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "name": "offset",
            "in": "query"
          },
          {
            "type": "string",
            "name": "search",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Get category list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/category"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "OauthSecurity": [
              "admin"
            ]
          }
        ],
        "tags": [
          "categories"
        ],
        "summary": "Add category",
        "operationId": "addCategory",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/category"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/categories/{id}": {
      "get": {
        "security": [],
        "tags": [
          "category"
        ],
        "summary": "Get category by ID",
        "operationId": "getCategory",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/category"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "OauthSecurity": [
              "admin"
            ]
          }
        ],
        "tags": [
          "category"
        ],
        "summary": "Edit category by ID",
        "operationId": "editCategory",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/category"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "OauthSecurity": [
              "admin"
            ]
          }
        ],
        "tags": [
          "category"
        ],
        "summary": "Delete category by ID",
        "operationId": "deleteCategory",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/login": {
      "get": {
        "security": [],
        "tags": [
          "auth"
        ],
        "summary": "Login through oauth2 server",
        "operationId": "login",
        "responses": {
          "200": {
            "description": "Login",
            "schema": {
              "$ref": "#/definitions/principal"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/orders": {
      "get": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "orders"
        ],
        "summary": "List orders",
        "operationId": "listOrders",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 24,
            "name": "limit",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "name": "offset",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Get order list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/order"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "orders"
        ],
        "summary": "Add order",
        "operationId": "addOrder",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/order"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/order"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/orders/{id}": {
      "get": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "order"
        ],
        "summary": "Get order by ID",
        "operationId": "getOrder",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/order"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "order"
        ],
        "summary": "Edit order by ID",
        "operationId": "editOrder",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/order"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/order"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "order"
        ],
        "summary": "Delete order by ID",
        "operationId": "deleteOrder",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/payments": {
      "get": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "payments"
        ],
        "summary": "List payments",
        "operationId": "listPayments",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 24,
            "name": "limit",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "name": "offset",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Get payment list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/payment"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "payments"
        ],
        "summary": "Add payment",
        "operationId": "addPayment",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/payment"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/payment"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/payments/{id}": {
      "get": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "payment"
        ],
        "summary": "Get payment by ID",
        "operationId": "getPayment",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/payment"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "payment"
        ],
        "summary": "Edit payment by ID",
        "operationId": "editPayment",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/payment"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/payment"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "payment"
        ],
        "summary": "Delete payment by ID",
        "operationId": "deletePaymet",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/products": {
      "get": {
        "security": [],
        "tags": [
          "products"
        ],
        "summary": "List products",
        "operationId": "getProducts",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 24,
            "name": "limit",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "name": "offset",
            "in": "query"
          },
          {
            "type": "string",
            "name": "search",
            "in": "query"
          },
          {
            "type": "array",
            "items": {
              "type": "integer",
              "format": "int64"
            },
            "collectionFormat": "csv",
            "name": "categoryIds",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Get product list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/product"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "OauthSecurity": [
              "admin"
            ]
          }
        ],
        "tags": [
          "products"
        ],
        "summary": "Add product",
        "operationId": "addProduct",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/product"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/product"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/products/{id}": {
      "get": {
        "security": [],
        "tags": [
          "product"
        ],
        "summary": "Get product by ID",
        "operationId": "getProduct",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/product"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "OauthSecurity": [
              "admin"
            ]
          }
        ],
        "tags": [
          "product"
        ],
        "summary": "Edit product by ID",
        "operationId": "editProduct",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/product"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/product"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "OauthSecurity": [
              "admin"
            ]
          }
        ],
        "tags": [
          "product"
        ],
        "summary": "Delete product by ID",
        "operationId": "deleteProduct",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users": {
      "get": {
        "security": [
          {
            "OauthSecurity": [
              "admin"
            ]
          }
        ],
        "tags": [
          "users"
        ],
        "summary": "List users",
        "operationId": "listUsers",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 24,
            "name": "limit",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "name": "offset",
            "in": "query"
          },
          {
            "type": "string",
            "name": "search",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Get user list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/user"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "OauthSecurity": [
              "admin"
            ]
          }
        ],
        "tags": [
          "users"
        ],
        "summary": "Add user",
        "operationId": "addUser",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/user"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "user"
        ],
        "summary": "Get user by ID",
        "operationId": "getUser",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "user"
        ],
        "summary": "Edit user by ID",
        "operationId": "editUser",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/user"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "user"
        ],
        "summary": "Delete user by ID",
        "operationId": "deleteUser",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "category": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "description": {
          "type": "string",
          "minLength": 1
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "title": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "httpcode": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "order": {
      "type": "object",
      "required": [
        "products",
        "totalPrice",
        "deliveryInfo"
      ],
      "properties": {
        "dateCreated": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "dateUpdated": {
          "type": "integer",
          "format": "int64"
        },
        "deliveryInfo": {
          "type": "string",
          "minLength": 10
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "products": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/orderedProduct"
          }
        },
        "status": {
          "type": "string"
        },
        "totalPrice": {
          "type": "number"
        },
        "userId": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "orderedProduct": {
      "type": "object",
      "required": [
        "productId",
        "quantity",
        "totalPrice"
      ],
      "properties": {
        "inStock": {
          "type": "boolean",
          "readOnly": true
        },
        "orderId": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "productId": {
          "type": "integer",
          "format": "int64"
        },
        "productName": {
          "type": "string",
          "readOnly": true
        },
        "quantity": {
          "type": "integer"
        },
        "totalPrice": {
          "type": "number"
        }
      }
    },
    "payment": {
      "type": "object",
      "required": [
        "orderId",
        "amount"
      ],
      "properties": {
        "amount": {
          "type": "number"
        },
        "dateCreated": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "dateUpdated": {
          "type": "integer",
          "format": "int64"
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "orderId": {
          "type": "integer",
          "format": "int64"
        },
        "status": {
          "type": "string"
        },
        "userId": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "principal": {
      "type": "object",
      "$ref": "#/definitions/user_info"
    },
    "product": {
      "type": "object",
      "required": [
        "title",
        "description"
      ],
      "properties": {
        "categoryIds": {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int64"
          }
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "images": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "numberInStock": {
          "type": "integer"
        },
        "price": {
          "type": "number"
        },
        "title": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "user": {
      "type": "object",
      "required": [
        "email"
      ],
      "properties": {
        "dateCreated": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "dateUpdated": {
          "type": "integer",
          "format": "int64"
        },
        "email": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "name": {
          "type": "string"
        }
      }
    },
    "user_info": {
      "type": "object",
      "properties": {
        "ACLRole": {
          "type": "string"
        },
        "accessToken": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "emailVerified": {
          "type": "boolean"
        },
        "familyName": {
          "type": "string"
        },
        "givenName": {
          "type": "string"
        },
        "locale": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "picture": {
          "type": "string"
        },
        "sub": {
          "type": "string"
        },
        "user": {
          "type": "object",
          "$ref": "#/definitions/user"
        }
      }
    }
  },
  "securityDefinitions": {
    "OauthSecurity": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/v2/auth",
      "tokenUrl": "https://oauth2.googleapis.com/token",
      "scopes": {
        "admin": "Admin scope",
        "private": "Private scope",
        "user": "User scope"
      }
    }
  },
  "security": [
    {
      "OauthSecurity": [
        "user"
      ]
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Capstone project: back-end",
    "title": "E-Store Back-end",
    "version": "1.0.0"
  },
  "paths": {
    "/auth/cb": {
      "get": {
        "security": [],
        "tags": [
          "auth"
        ],
        "summary": "Obtain access token",
        "operationId": "getAccessToken",
        "responses": {
          "200": {
            "description": "Login",
            "schema": {
              "$ref": "#/definitions/principal"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/categories": {
      "get": {
        "security": [],
        "tags": [
          "categories"
        ],
        "summary": "List categories",
        "operationId": "listCategories",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 24,
            "name": "limit",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "name": "offset",
            "in": "query"
          },
          {
            "type": "string",
            "name": "search",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Get category list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/category"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "OauthSecurity": [
              "admin"
            ]
          }
        ],
        "tags": [
          "categories"
        ],
        "summary": "Add category",
        "operationId": "addCategory",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/category"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/categories/{id}": {
      "get": {
        "security": [],
        "tags": [
          "category"
        ],
        "summary": "Get category by ID",
        "operationId": "getCategory",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/category"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "OauthSecurity": [
              "admin"
            ]
          }
        ],
        "tags": [
          "category"
        ],
        "summary": "Edit category by ID",
        "operationId": "editCategory",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/category"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "OauthSecurity": [
              "admin"
            ]
          }
        ],
        "tags": [
          "category"
        ],
        "summary": "Delete category by ID",
        "operationId": "deleteCategory",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/login": {
      "get": {
        "security": [],
        "tags": [
          "auth"
        ],
        "summary": "Login through oauth2 server",
        "operationId": "login",
        "responses": {
          "200": {
            "description": "Login",
            "schema": {
              "$ref": "#/definitions/principal"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/orders": {
      "get": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "orders"
        ],
        "summary": "List orders",
        "operationId": "listOrders",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 24,
            "name": "limit",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "name": "offset",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Get order list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/order"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "orders"
        ],
        "summary": "Add order",
        "operationId": "addOrder",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/order"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/order"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/orders/{id}": {
      "get": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "order"
        ],
        "summary": "Get order by ID",
        "operationId": "getOrder",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/order"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "order"
        ],
        "summary": "Edit order by ID",
        "operationId": "editOrder",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/order"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/order"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "order"
        ],
        "summary": "Delete order by ID",
        "operationId": "deleteOrder",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/payments": {
      "get": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "payments"
        ],
        "summary": "List payments",
        "operationId": "listPayments",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 24,
            "name": "limit",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "name": "offset",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Get payment list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/payment"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "payments"
        ],
        "summary": "Add payment",
        "operationId": "addPayment",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/payment"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/payment"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/payments/{id}": {
      "get": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "payment"
        ],
        "summary": "Get payment by ID",
        "operationId": "getPayment",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/payment"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "payment"
        ],
        "summary": "Edit payment by ID",
        "operationId": "editPayment",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/payment"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/payment"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "payment"
        ],
        "summary": "Delete payment by ID",
        "operationId": "deletePaymet",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/products": {
      "get": {
        "security": [],
        "tags": [
          "products"
        ],
        "summary": "List products",
        "operationId": "getProducts",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 24,
            "name": "limit",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "name": "offset",
            "in": "query"
          },
          {
            "type": "string",
            "name": "search",
            "in": "query"
          },
          {
            "type": "array",
            "items": {
              "type": "integer",
              "format": "int64"
            },
            "collectionFormat": "csv",
            "name": "categoryIds",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Get product list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/product"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "OauthSecurity": [
              "admin"
            ]
          }
        ],
        "tags": [
          "products"
        ],
        "summary": "Add product",
        "operationId": "addProduct",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/product"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/product"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/products/{id}": {
      "get": {
        "security": [],
        "tags": [
          "product"
        ],
        "summary": "Get product by ID",
        "operationId": "getProduct",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/product"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "OauthSecurity": [
              "admin"
            ]
          }
        ],
        "tags": [
          "product"
        ],
        "summary": "Edit product by ID",
        "operationId": "editProduct",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/product"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/product"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "OauthSecurity": [
              "admin"
            ]
          }
        ],
        "tags": [
          "product"
        ],
        "summary": "Delete product by ID",
        "operationId": "deleteProduct",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users": {
      "get": {
        "security": [
          {
            "OauthSecurity": [
              "admin"
            ]
          }
        ],
        "tags": [
          "users"
        ],
        "summary": "List users",
        "operationId": "listUsers",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 24,
            "name": "limit",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "name": "offset",
            "in": "query"
          },
          {
            "type": "string",
            "name": "search",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Get user list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/user"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "OauthSecurity": [
              "admin"
            ]
          }
        ],
        "tags": [
          "users"
        ],
        "summary": "Add user",
        "operationId": "addUser",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/user"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "user"
        ],
        "summary": "Get user by ID",
        "operationId": "getUser",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "user"
        ],
        "summary": "Edit user by ID",
        "operationId": "editUser",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/user"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "OauthSecurity": [
              "admin",
              "private"
            ]
          }
        ],
        "tags": [
          "user"
        ],
        "summary": "Delete user by ID",
        "operationId": "deleteUser",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "category": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "description": {
          "type": "string",
          "minLength": 1
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "title": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "httpcode": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "order": {
      "type": "object",
      "required": [
        "products",
        "totalPrice",
        "deliveryInfo"
      ],
      "properties": {
        "dateCreated": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "dateUpdated": {
          "type": "integer",
          "format": "int64"
        },
        "deliveryInfo": {
          "type": "string",
          "minLength": 10
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "products": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/orderedProduct"
          }
        },
        "status": {
          "type": "string"
        },
        "totalPrice": {
          "type": "number"
        },
        "userId": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "orderedProduct": {
      "type": "object",
      "required": [
        "productId",
        "quantity",
        "totalPrice"
      ],
      "properties": {
        "inStock": {
          "type": "boolean",
          "readOnly": true
        },
        "orderId": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "productId": {
          "type": "integer",
          "format": "int64"
        },
        "productName": {
          "type": "string",
          "readOnly": true
        },
        "quantity": {
          "type": "integer"
        },
        "totalPrice": {
          "type": "number"
        }
      }
    },
    "payment": {
      "type": "object",
      "required": [
        "orderId",
        "amount"
      ],
      "properties": {
        "amount": {
          "type": "number"
        },
        "dateCreated": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "dateUpdated": {
          "type": "integer",
          "format": "int64"
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "orderId": {
          "type": "integer",
          "format": "int64"
        },
        "status": {
          "type": "string"
        },
        "userId": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "principal": {
      "type": "object",
      "$ref": "#/definitions/user_info"
    },
    "product": {
      "type": "object",
      "required": [
        "title",
        "description"
      ],
      "properties": {
        "categoryIds": {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int64"
          }
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "images": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "numberInStock": {
          "type": "integer"
        },
        "price": {
          "type": "number"
        },
        "title": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "user": {
      "type": "object",
      "required": [
        "email"
      ],
      "properties": {
        "dateCreated": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "dateUpdated": {
          "type": "integer",
          "format": "int64"
        },
        "email": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "name": {
          "type": "string"
        }
      }
    },
    "user_info": {
      "type": "object",
      "properties": {
        "ACLRole": {
          "type": "string"
        },
        "accessToken": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "emailVerified": {
          "type": "boolean"
        },
        "familyName": {
          "type": "string"
        },
        "givenName": {
          "type": "string"
        },
        "locale": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "picture": {
          "type": "string"
        },
        "sub": {
          "type": "string"
        },
        "user": {
          "type": "object",
          "$ref": "#/definitions/user"
        }
      }
    }
  },
  "securityDefinitions": {
    "OauthSecurity": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/v2/auth",
      "tokenUrl": "https://oauth2.googleapis.com/token",
      "scopes": {
        "admin": "Admin scope",
        "private": "Private scope",
        "user": "User scope"
      }
    }
  },
  "security": [
    {
      "OauthSecurity": [
        "user"
      ]
    }
  ]
}`))
}
