// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CheckoutSession checkout session
//
// swagger:model checkout_session
type CheckoutSession struct {

	// customer email
	CustomerEmail string `json:"customer_email,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this checkout session
func (m *CheckoutSession) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this checkout session based on context it is used
func (m *CheckoutSession) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CheckoutSession) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CheckoutSession) UnmarshalBinary(b []byte) error {
	var res CheckoutSession
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
