// Code generated by go-swagger; DO NOT EDIT.

package checkout

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"estore-backend/server/models"
)

// AddCheckoutSessionHandlerFunc turns a function with the right signature into a add checkout session handler
type AddCheckoutSessionHandlerFunc func(AddCheckoutSessionParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn AddCheckoutSessionHandlerFunc) Handle(params AddCheckoutSessionParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// AddCheckoutSessionHandler interface for that can handle valid add checkout session params
type AddCheckoutSessionHandler interface {
	Handle(AddCheckoutSessionParams, *models.Principal) middleware.Responder
}

// NewAddCheckoutSession creates a new http.Handler for the add checkout session operation
func NewAddCheckoutSession(ctx *middleware.Context, handler AddCheckoutSessionHandler) *AddCheckoutSession {
	return &AddCheckoutSession{Context: ctx, Handler: handler}
}

/*
	AddCheckoutSession swagger:route POST /checkout/session checkout addCheckoutSession

Add checkout session
*/
type AddCheckoutSession struct {
	Context *middleware.Context
	Handler AddCheckoutSessionHandler
}

func (o *AddCheckoutSession) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddCheckoutSessionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
