// Code generated by go-swagger; DO NOT EDIT.

package checkout

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"estore-backend/server/models"
)

// AddCheckoutSessionCreatedCode is the HTTP code returned for type AddCheckoutSessionCreated
const AddCheckoutSessionCreatedCode int = 201

/*
AddCheckoutSessionCreated Created

swagger:response addCheckoutSessionCreated
*/
type AddCheckoutSessionCreated struct {

	/*
	  In: Body
	*/
	Payload *models.CheckoutSessionSecret `json:"body,omitempty"`
}

// NewAddCheckoutSessionCreated creates AddCheckoutSessionCreated with default headers values
func NewAddCheckoutSessionCreated() *AddCheckoutSessionCreated {

	return &AddCheckoutSessionCreated{}
}

// WithPayload adds the payload to the add checkout session created response
func (o *AddCheckoutSessionCreated) WithPayload(payload *models.CheckoutSessionSecret) *AddCheckoutSessionCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add checkout session created response
func (o *AddCheckoutSessionCreated) SetPayload(payload *models.CheckoutSessionSecret) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddCheckoutSessionCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
AddCheckoutSessionDefault error

swagger:response addCheckoutSessionDefault
*/
type AddCheckoutSessionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddCheckoutSessionDefault creates AddCheckoutSessionDefault with default headers values
func NewAddCheckoutSessionDefault(code int) *AddCheckoutSessionDefault {
	if code <= 0 {
		code = 500
	}

	return &AddCheckoutSessionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add checkout session default response
func (o *AddCheckoutSessionDefault) WithStatusCode(code int) *AddCheckoutSessionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add checkout session default response
func (o *AddCheckoutSessionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add checkout session default response
func (o *AddCheckoutSessionDefault) WithPayload(payload *models.Error) *AddCheckoutSessionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add checkout session default response
func (o *AddCheckoutSessionDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddCheckoutSessionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
