// Code generated by go-swagger; DO NOT EDIT.

package checkout

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetCheckoutSessionParams creates a new GetCheckoutSessionParams object
//
// There are no default values defined in the spec.
func NewGetCheckoutSessionParams() GetCheckoutSessionParams {

	return GetCheckoutSessionParams{}
}

// GetCheckoutSessionParams contains all the bound params for the get checkout session operation
// typically these are obtained from a http.Request
//
// swagger:parameters getCheckoutSession
type GetCheckoutSessionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: query
	*/
	SessionID *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetCheckoutSessionParams() beforehand.
func (o *GetCheckoutSessionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qSessionID, qhkSessionID, _ := qs.GetOK("session_id")
	if err := o.bindSessionID(qSessionID, qhkSessionID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSessionID binds and validates parameter SessionID from query.
func (o *GetCheckoutSessionParams) bindSessionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.SessionID = &raw

	return nil
}
