// Code generated by go-swagger; DO NOT EDIT.

package checkout

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"estore-backend/server/models"
)

// GetCheckoutSessionHandlerFunc turns a function with the right signature into a get checkout session handler
type GetCheckoutSessionHandlerFunc func(GetCheckoutSessionParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCheckoutSessionHandlerFunc) Handle(params GetCheckoutSessionParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetCheckoutSessionHandler interface for that can handle valid get checkout session params
type GetCheckoutSessionHandler interface {
	Handle(GetCheckoutSessionParams, *models.Principal) middleware.Responder
}

// NewGetCheckoutSession creates a new http.Handler for the get checkout session operation
func NewGetCheckoutSession(ctx *middleware.Context, handler GetCheckoutSessionHandler) *GetCheckoutSession {
	return &GetCheckoutSession{Context: ctx, Handler: handler}
}

/*
	GetCheckoutSession swagger:route GET /checkout/session checkout getCheckoutSession

Get checkout session
*/
type GetCheckoutSession struct {
	Context *middleware.Context
	Handler GetCheckoutSessionHandler
}

func (o *GetCheckoutSession) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCheckoutSessionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
