// Code generated by go-swagger; DO NOT EDIT.

package categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"estore-backend/server/models"
)

// AddCategoryCreatedCode is the HTTP code returned for type AddCategoryCreated
const AddCategoryCreatedCode int = 201

/*
AddCategoryCreated Created

swagger:response addCategoryCreated
*/
type AddCategoryCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Category `json:"body,omitempty"`
}

// NewAddCategoryCreated creates AddCategoryCreated with default headers values
func NewAddCategoryCreated() *AddCategoryCreated {

	return &AddCategoryCreated{}
}

// WithPayload adds the payload to the add category created response
func (o *AddCategoryCreated) WithPayload(payload *models.Category) *AddCategoryCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add category created response
func (o *AddCategoryCreated) SetPayload(payload *models.Category) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddCategoryCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
AddCategoryDefault error

swagger:response addCategoryDefault
*/
type AddCategoryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddCategoryDefault creates AddCategoryDefault with default headers values
func NewAddCategoryDefault(code int) *AddCategoryDefault {
	if code <= 0 {
		code = 500
	}

	return &AddCategoryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add category default response
func (o *AddCategoryDefault) WithStatusCode(code int) *AddCategoryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add category default response
func (o *AddCategoryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add category default response
func (o *AddCategoryDefault) WithPayload(payload *models.Error) *AddCategoryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add category default response
func (o *AddCategoryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddCategoryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
