// Code generated by go-swagger; DO NOT EDIT.

package payment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"estore-backend/server/models"
)

// DeletePaymetHandlerFunc turns a function with the right signature into a delete paymet handler
type DeletePaymetHandlerFunc func(DeletePaymetParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeletePaymetHandlerFunc) Handle(params DeletePaymetParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeletePaymetHandler interface for that can handle valid delete paymet params
type DeletePaymetHandler interface {
	Handle(DeletePaymetParams, *models.Principal) middleware.Responder
}

// NewDeletePaymet creates a new http.Handler for the delete paymet operation
func NewDeletePaymet(ctx *middleware.Context, handler DeletePaymetHandler) *DeletePaymet {
	return &DeletePaymet{Context: ctx, Handler: handler}
}

/*
	DeletePaymet swagger:route DELETE /payments/{id} payment deletePaymet

Delete payment by ID
*/
type DeletePaymet struct {
	Context *middleware.Context
	Handler DeletePaymetHandler
}

func (o *DeletePaymet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeletePaymetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
