// Code generated by go-swagger; DO NOT EDIT.

package payment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"estore-backend/server/models"
)

// DeletePaymetNoContentCode is the HTTP code returned for type DeletePaymetNoContent
const DeletePaymetNoContentCode int = 204

/*
DeletePaymetNoContent Deleted

swagger:response deletePaymetNoContent
*/
type DeletePaymetNoContent struct {
}

// NewDeletePaymetNoContent creates DeletePaymetNoContent with default headers values
func NewDeletePaymetNoContent() *DeletePaymetNoContent {

	return &DeletePaymetNoContent{}
}

// WriteResponse to the client
func (o *DeletePaymetNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*
DeletePaymetDefault Error

swagger:response deletePaymetDefault
*/
type DeletePaymetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeletePaymetDefault creates DeletePaymetDefault with default headers values
func NewDeletePaymetDefault(code int) *DeletePaymetDefault {
	if code <= 0 {
		code = 500
	}

	return &DeletePaymetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete paymet default response
func (o *DeletePaymetDefault) WithStatusCode(code int) *DeletePaymetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete paymet default response
func (o *DeletePaymetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete paymet default response
func (o *DeletePaymetDefault) WithPayload(payload *models.Error) *DeletePaymetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete paymet default response
func (o *DeletePaymetDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePaymetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
