// Code generated by go-swagger; DO NOT EDIT.

package payment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"estore-backend/server/models"
)

// EditPaymentOKCode is the HTTP code returned for type EditPaymentOK
const EditPaymentOKCode int = 200

/*
EditPaymentOK OK

swagger:response editPaymentOK
*/
type EditPaymentOK struct {

	/*
	  In: Body
	*/
	Payload *models.Payment `json:"body,omitempty"`
}

// NewEditPaymentOK creates EditPaymentOK with default headers values
func NewEditPaymentOK() *EditPaymentOK {

	return &EditPaymentOK{}
}

// WithPayload adds the payload to the edit payment o k response
func (o *EditPaymentOK) WithPayload(payload *models.Payment) *EditPaymentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the edit payment o k response
func (o *EditPaymentOK) SetPayload(payload *models.Payment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *EditPaymentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
EditPaymentDefault Error

swagger:response editPaymentDefault
*/
type EditPaymentDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewEditPaymentDefault creates EditPaymentDefault with default headers values
func NewEditPaymentDefault(code int) *EditPaymentDefault {
	if code <= 0 {
		code = 500
	}

	return &EditPaymentDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the edit payment default response
func (o *EditPaymentDefault) WithStatusCode(code int) *EditPaymentDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the edit payment default response
func (o *EditPaymentDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the edit payment default response
func (o *EditPaymentDefault) WithPayload(payload *models.Error) *EditPaymentDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the edit payment default response
func (o *EditPaymentDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *EditPaymentDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
