// Code generated by go-swagger; DO NOT EDIT.

package payment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"estore-backend/server/models"
)

// GetPaymentOKCode is the HTTP code returned for type GetPaymentOK
const GetPaymentOKCode int = 200

/*
GetPaymentOK OK

swagger:response getPaymentOK
*/
type GetPaymentOK struct {

	/*
	  In: Body
	*/
	Payload *models.Payment `json:"body,omitempty"`
}

// NewGetPaymentOK creates GetPaymentOK with default headers values
func NewGetPaymentOK() *GetPaymentOK {

	return &GetPaymentOK{}
}

// WithPayload adds the payload to the get payment o k response
func (o *GetPaymentOK) WithPayload(payload *models.Payment) *GetPaymentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get payment o k response
func (o *GetPaymentOK) SetPayload(payload *models.Payment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPaymentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetPaymentDefault Error

swagger:response getPaymentDefault
*/
type GetPaymentDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPaymentDefault creates GetPaymentDefault with default headers values
func NewGetPaymentDefault(code int) *GetPaymentDefault {
	if code <= 0 {
		code = 500
	}

	return &GetPaymentDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get payment default response
func (o *GetPaymentDefault) WithStatusCode(code int) *GetPaymentDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get payment default response
func (o *GetPaymentDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get payment default response
func (o *GetPaymentDefault) WithPayload(payload *models.Error) *GetPaymentDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get payment default response
func (o *GetPaymentDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPaymentDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
