// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"estore-backend/server/models"
)

// DeleteOrderNoContentCode is the HTTP code returned for type DeleteOrderNoContent
const DeleteOrderNoContentCode int = 204

/*
DeleteOrderNoContent Deleted

swagger:response deleteOrderNoContent
*/
type DeleteOrderNoContent struct {
}

// NewDeleteOrderNoContent creates DeleteOrderNoContent with default headers values
func NewDeleteOrderNoContent() *DeleteOrderNoContent {

	return &DeleteOrderNoContent{}
}

// WriteResponse to the client
func (o *DeleteOrderNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*
DeleteOrderDefault Error

swagger:response deleteOrderDefault
*/
type DeleteOrderDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteOrderDefault creates DeleteOrderDefault with default headers values
func NewDeleteOrderDefault(code int) *DeleteOrderDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteOrderDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete order default response
func (o *DeleteOrderDefault) WithStatusCode(code int) *DeleteOrderDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete order default response
func (o *DeleteOrderDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete order default response
func (o *DeleteOrderDefault) WithPayload(payload *models.Error) *DeleteOrderDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete order default response
func (o *DeleteOrderDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteOrderDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
