// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"estore-backend/server/models"
)

// DeleteOrderHandlerFunc turns a function with the right signature into a delete order handler
type DeleteOrderHandlerFunc func(DeleteOrderParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteOrderHandlerFunc) Handle(params DeleteOrderParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteOrderHandler interface for that can handle valid delete order params
type DeleteOrderHandler interface {
	Handle(DeleteOrderParams, *models.Principal) middleware.Responder
}

// NewDeleteOrder creates a new http.Handler for the delete order operation
func NewDeleteOrder(ctx *middleware.Context, handler DeleteOrderHandler) *DeleteOrder {
	return &DeleteOrder{Context: ctx, Handler: handler}
}

/*
	DeleteOrder swagger:route DELETE /orders/{id} order deleteOrder

Delete order by ID
*/
type DeleteOrder struct {
	Context *middleware.Context
	Handler DeleteOrderHandler
}

func (o *DeleteOrder) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteOrderParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
