// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewProcessStripePaymentParams creates a new ProcessStripePaymentParams object
//
// There are no default values defined in the spec.
func NewProcessStripePaymentParams() ProcessStripePaymentParams {

	return ProcessStripePaymentParams{}
}

// ProcessStripePaymentParams contains all the bound params for the process stripe payment operation
// typically these are obtained from a http.Request
//
// swagger:parameters processStripePayment
type ProcessStripePaymentParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: header
	*/
	StripeSignature string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewProcessStripePaymentParams() beforehand.
func (o *ProcessStripePaymentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindStripeSignature(r.Header[http.CanonicalHeaderKey("Stripe-Signature")], true, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindStripeSignature binds and validates parameter StripeSignature from header.
func (o *ProcessStripePaymentParams) bindStripeSignature(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("Stripe-Signature", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("Stripe-Signature", "header", raw); err != nil {
		return err
	}
	o.StripeSignature = raw

	return nil
}
