// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"estore-backend/server/models"
)

// ProcessStripePaymentOKCode is the HTTP code returned for type ProcessStripePaymentOK
const ProcessStripePaymentOKCode int = 200

/*
ProcessStripePaymentOK Processed

swagger:response processStripePaymentOK
*/
type ProcessStripePaymentOK struct {
}

// NewProcessStripePaymentOK creates ProcessStripePaymentOK with default headers values
func NewProcessStripePaymentOK() *ProcessStripePaymentOK {

	return &ProcessStripePaymentOK{}
}

// WriteResponse to the client
func (o *ProcessStripePaymentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
ProcessStripePaymentDefault error

swagger:response processStripePaymentDefault
*/
type ProcessStripePaymentDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewProcessStripePaymentDefault creates ProcessStripePaymentDefault with default headers values
func NewProcessStripePaymentDefault(code int) *ProcessStripePaymentDefault {
	if code <= 0 {
		code = 500
	}

	return &ProcessStripePaymentDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the process stripe payment default response
func (o *ProcessStripePaymentDefault) WithStatusCode(code int) *ProcessStripePaymentDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the process stripe payment default response
func (o *ProcessStripePaymentDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the process stripe payment default response
func (o *ProcessStripePaymentDefault) WithPayload(payload *models.Error) *ProcessStripePaymentDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the process stripe payment default response
func (o *ProcessStripePaymentDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProcessStripePaymentDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
