// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"estore-backend/server/models"
)

// AddProductCreatedCode is the HTTP code returned for type AddProductCreated
const AddProductCreatedCode int = 201

/*
AddProductCreated Created

swagger:response addProductCreated
*/
type AddProductCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Product `json:"body,omitempty"`
}

// NewAddProductCreated creates AddProductCreated with default headers values
func NewAddProductCreated() *AddProductCreated {

	return &AddProductCreated{}
}

// WithPayload adds the payload to the add product created response
func (o *AddProductCreated) WithPayload(payload *models.Product) *AddProductCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add product created response
func (o *AddProductCreated) SetPayload(payload *models.Product) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddProductCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
AddProductDefault error

swagger:response addProductDefault
*/
type AddProductDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddProductDefault creates AddProductDefault with default headers values
func NewAddProductDefault(code int) *AddProductDefault {
	if code <= 0 {
		code = 500
	}

	return &AddProductDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add product default response
func (o *AddProductDefault) WithStatusCode(code int) *AddProductDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add product default response
func (o *AddProductDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add product default response
func (o *AddProductDefault) WithPayload(payload *models.Error) *AddProductDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add product default response
func (o *AddProductDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddProductDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
